#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
DEFAULT_RELEASE_DIR="$ROOT_DIR/mprove_data/mcli-release"
DEFAULT_OUTPUT_FILE="$ROOT_DIR/mprove_data/mcli-release/mprove-cli.rb"

VERSION=""
RELEASE_DIR="$DEFAULT_RELEASE_DIR"
OUTPUT_FILE="$DEFAULT_OUTPUT_FILE"
SKIP_SOURCE_CHECKSUM=0

usage() {
  cat <<'EOF'
Usage: scripts/dev/release-homebrew-mprove.sh [version] [options]

Creates a Homebrew formula file for a published mprove-cli release.

Arguments:
  version                 Optional version. Defaults to package.json version. A cli- prefix is stripped.

Options:
  --release-dir <path>    Directory with mprove-cli release archives and checksums.
                          Default: mprove_data/mcli-release
  --output <path>         Formula file to write.
                          Default: mprove_data/mcli-release/mprove-cli.rb
  --skip-source-checksum  Do not download the GitHub source archive checksum.
                          Uses the linux-amd64 archive as the top-level formula URL.
  -h, --help              Show this help.

Expected release files:
  mprove-cli-<version>-darwin-amd64.tar.gz
  mprove-cli-<version>-darwin-arm64.tar.gz
  mprove-cli-<version>-linux-amd64.tar.gz
  mprove-cli-<version>-checksums.txt

EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --release-dir)
      RELEASE_DIR="${2:?Error: --release-dir requires a path}"
      shift
      ;;
    --output)
      OUTPUT_FILE="${2:?Error: --output requires a path}"
      shift
      ;;
    --skip-source-checksum)
      SKIP_SOURCE_CHECKSUM=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [ -n "$VERSION" ]; then
        echo "Error: unexpected argument: $1"
        usage
        exit 1
      fi
      VERSION="$1"
      ;;
  esac
  shift
done

need_command() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "Error: required command not found: $command_name"
    exit 1
  fi
}

need_command mkdir
need_command node
need_command sha256sum

if [ "$SKIP_SOURCE_CHECKSUM" -eq 0 ]; then
  need_command curl
fi

if [ -z "$VERSION" ]; then
  VERSION="$(cd "$ROOT_DIR" && node -e "console.log(require('./package.json').version)")"
fi

VERSION="${VERSION#cli-}"

if [ -z "$VERSION" ]; then
  echo "Error: version is empty"
  exit 1
fi

CHECKSUM_FILE="$RELEASE_DIR/mprove-cli-$VERSION-checksums.txt"

if [ ! -f "$CHECKSUM_FILE" ]; then
  echo "Error: checksum file not found: $CHECKSUM_FILE"
  echo "Run scripts/dev/build-mprove-cli-release.sh $VERSION first."
  exit 1
fi

get_checksum() {
  local file_name="$1"
  local checksum=""

  checksum="$(while read -r hash name; do
    if [ "$name" = "$file_name" ]; then
      printf '%s' "$hash"
      break
    fi
  done < "$CHECKSUM_FILE")"

  if [ -z "$checksum" ]; then
    echo "Error: checksum not found for $file_name in $CHECKSUM_FILE" >&2
    exit 1
  fi

  printf '%s' "$checksum"
}

DARWIN_AMD64_FILE="mprove-cli-$VERSION-darwin-amd64.tar.gz"
DARWIN_ARM64_FILE="mprove-cli-$VERSION-darwin-arm64.tar.gz"
LINUX_AMD64_FILE="mprove-cli-$VERSION-linux-amd64.tar.gz"

DARWIN_AMD64_SHA="$(get_checksum "$DARWIN_AMD64_FILE")"
DARWIN_ARM64_SHA="$(get_checksum "$DARWIN_ARM64_FILE")"
LINUX_AMD64_SHA="$(get_checksum "$LINUX_AMD64_FILE")"

RELEASE_BASE_URL="https://github.com/mprove-io/mprove-cli/releases/download/$VERSION"
SOURCE_URL="https://github.com/mprove-io/mprove-cli/archive/refs/tags/$VERSION.tar.gz"
SOURCE_SHA=""
TOP_URL="$SOURCE_URL"

if [ "$SKIP_SOURCE_CHECKSUM" -eq 0 ]; then
  SOURCE_TARBALL="$(mktemp)"
  trap 'rm -f "$SOURCE_TARBALL"' EXIT

  echo "Downloading source archive for checksum..."
  curl -fsSL "$SOURCE_URL" -o "$SOURCE_TARBALL"
  SOURCE_SHA="$(sha256sum "$SOURCE_TARBALL" | cut -d ' ' -f 1)"
else
  TOP_URL="$RELEASE_BASE_URL/$LINUX_AMD64_FILE"
  SOURCE_SHA="$LINUX_AMD64_SHA"
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MproveCli < Formula
  desc "Mprove cli files"
  homepage "https://github.com/mprove-io/mprove-cli"
  url "$TOP_URL"
  version "$VERSION"
  sha256 "$SOURCE_SHA"

  on_macos do
    on_intel do
      url "$RELEASE_BASE_URL/$DARWIN_AMD64_FILE"
      sha256 "$DARWIN_AMD64_SHA"
    end

    on_arm do
      url "$RELEASE_BASE_URL/$DARWIN_ARM64_FILE"
      sha256 "$DARWIN_ARM64_SHA"
    end
  end

  on_linux do
    on_intel do
      url "$RELEASE_BASE_URL/$LINUX_AMD64_FILE"
      sha256 "$LINUX_AMD64_SHA"
    end
  end

  def install
    bin.install "mprove"
  end

  test do
    assert_match "mproveCLI", shell_output("#{bin}/mprove version")
  end
end
EOF

echo "Homebrew formula created: $OUTPUT_FILE"
